/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface SassOptions {
  file: string
  sourceMap: boolean
  style: string
  syntax: string
}
export interface LegacySassOptions {
  charset: boolean
  data: string
  file: string
  includePaths: Array<string>
  indentedSyntax: boolean
  omitSourceMapUrl: boolean
  outFile: string
  outputStyle: string
  sourceMap: boolean
  sourceMapContents: boolean
  sourceMapEmbed: boolean
}
export interface SassError {
  file?: string
  line?: number
  column?: number
  message?: string
  formatted?: string
}
export interface SassStats {
  includedFiles: Array<string>
}
export interface SassResult {
  css: string
  loadedUrls: Array<string>
  sourceMap: string
  stats: SassStats
  map: string
}
export interface CompileResult {
  success?: SassResult
  failure?: SassError
}
export function compile(source: string, options?: SassOptions | undefined | null): CompileResult
export function compileLegacy(source: string, options?: LegacySassOptions | undefined | null): CompileResult
